project:
  type: website

website:
  title: "Documentation de CIME"
  favicon: img/icon-color.png
  repo-url: https://github.com/ujubib/Quarto_Documentation-CIME-OmekaS/
  repo-subdir: /QuartoDocCIME/
  repo-actions: [source, edit, issue]
  open-graph: true
  reader-mode: true
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  navbar:
    logo: img/UPPA_logo.png
    search: true
    pinned: false
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: À propos

format:
  html:
    tbl-cap-location: top
    mainfont: calibri
    grid:
      sidebar-width: 400px
      body-width: 900px
      margin-width: 400px
      gutter-width: 1.5rem
    theme:
      light: flatly
      dark: solar
    css: styles.css
    toc: true
    toc-depth: 5
    toc-expand: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    lightbox: true
    comments:
      hypothesis: true
  pdf:
    tbl-cap-location: top
    documentclass: scrartcl
    toc: true
    toc-depth: 5
    links-as-notes: true

