project:
  type: website
  output-dir: _site
  resources: 
    - ".csv"

execute:
  freeze: auto

website:
  title: "Documentation de CIME"
  favicon: img/icon-color.png
  repo-url: https://github.com/ujubib/Quarto_Documentation-CIME-OmekaS/
  repo-subdir: /QuartoDocCIME/
  repo-actions: [source, edit, issue]
  open-graph: true
  reader-mode: true
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  page-footer:
    background: FloralWhite
  navbar:
    logo: img/UPPA_logo.png
    search: true
    pinned: false
    left:
      - href: about.qmd
        text: À propos
  sidebar:
    style: "floating"
    background: FloralWhite
    collapse-level: 2
    contents:
      - section: "Que déposer ?"
        contents: "que/*"
      - section: "Qui dépose ?"
        contents: "qui/*"
      - section: "Comment déposer ?"
        contents: "comment/*"
      - section: "Omeka S"
        contents: "omeka/*"
#    tools:
#      - icon: box-arrow-up-right
#        href: https://kumbuka.univ-pau.fr

format:
  html:
    code-tools: false
    code-fold: true
    tbl-cap-location: top
    mainfont: calibri
    backgroundcolor: FloralWhite
    grid:
      sidebar-width: 400px
      body-width: 900px
      margin-width: 400px
      gutter-width: 1.5rem
    theme:
      light: flatly
      dark: solar
    filters:
     - nutshell
    css: styles.css
    toc: true
    toc-depth: 5
    toc-title: Sommaire
    toc-expand: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    lightbox: true
    comments:
      hypothesis: true
  pdf:
    tbl-cap-location: top
    documentclass: scrartcl
    toc: true
    toc-depth: 5
    toc-title: Sommaire
    lot: false
    lof: false
    links-as-notes: true
  docx:
    toc: true
    toc-depth: 5
    toc-title: Sommaire
    notes-after-punctuation: false

